# Generated by Django 5.0 on 2023-12-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todolist_task_assign_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Username',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
